---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cerulean-shift
# description will be included in the image's metadata
description: Fedora Universal Blue with Hyprland, Niri and Cosmic.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    base: main
    install:
      - zenergy
      - ryzen-smu

  - type: bling
    install:
        - 1password # install 1Password (stable) and `op` CLI tool

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      copr:
        enable:
          - tofik/nwg-shell
          - tofik/sway
          - solopasha/hyprland
          - yalter/niri
          - markupstart/SwayOSD
    install:
      packages:
        - mako
        # Core Hyprland Components
        - aquamarine
        - hyprland
        - xdg-desktop-portal-hyprland
        # Extended Hyprland Services
        - hyprcursor
        - hyprsysteminfo
        - hyprland-plugins
        - hypridle
        - hyprlock
        - hyprpolkitagent
        - hyprutils
        - hyprland-qtutils
        - hyprland-qt-support
        # - nwg-look
        # tofik/sway
        - gtklock
        - gtklock-userinfo-module
        - gtklock-powerbar-module
        - gammastep
        - gammastep-indicator
        - niri
        - waybar
        - xdg-desktop-portal-gtk
        - swww
        - gnome-disk-utility
    group-install:
      with-optional: false
      packages:
        - cosmic-desktop
        - virtualization

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: os-release
    properties:
      ID: cerulean_shift
      NAME: CeruleanShift
      PRETTY_NAME: Cerulean Shift

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

